### ISSUE TITLE
csv.gz support 

### ISSUE THREAD

**Issue by radio1988** [theislab/dca#7]
Hello, 

The DCA seems only supporting csv rather than csv.gz
I have very large csv files to begin with
Is it possible to support csv.gz?

Thanks!
Ray

**Comment by gokceneraslan** [comment]
Hi Ray,

Thanks for the report. csv/tsv files with gzip or bzip2 compression are not supported for now, because I use scanpy's `read()` function in DCA, which actually uses `anndata.read()` and gzip/bzip2 is not supported there. It's a trivial fix though.

I'll keep this open and file an issue on anndata repository.

**Comment by gokceneraslan** [comment]
gz and bz2 compression support is now added to anndata and scanpy packages. You can use compressed files with the next release of scanpy and anndata.
